name: Devops-ye-bate
on:
  push:
    branches: ["develop","master"]
jobs:
  devops:
    name: Tests - Unit & Integration & Sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: actions/setup-java@1
        with:
          java-version: 17
      - name: Unit & Integration tests
        run: |
          mvn clean
          mvn -B verify