name: Devops-ye-bate
on:
  push:
    branches: ["develop","release-*"]
jobs:
  devops:
    name: Tests - Unit & Integration & Sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Unit & Integration tests
        run: |
          mvn clean
          mvn -B verify
      - name: Sonar
        if: success()
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=WolfYe98_iwvg-devops-ye-bate
          -Dsonar.organization=wolfye98
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}